#!/bin/bash
set +x 
# Initialize database if not present
PSQL_IP=$DB_PORT_5432_TCP_ADDR
PSQL_PORT=$DB_PORT_5432_TCP_PORT
echo "$PSQL_IP:*:$DB_ENV_DB:$DB_ENV_DBUSER:$DB_ENV_DBPASS" > $HOME/.pgpas

RETURN=1
while [ $RETURN -gt 0 ]
do
  echo "Waiting for database..."
  sleep 1;
  CDB_EXISTS=`PGPASSWORD="$DB_ENV_DBPASS" psql -h $PSQL_IP -p $PSQL_PORT -U $DB_ENV_DBUSER -w -l 2>&1 | grep crucible | wc -l`
  RETURN=$?
done

# Import crowd.crt into java cacerts
keytool --import --file /config/crowd.crt --alias crowd.ovyka.com --keystore /usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts --storepass changeit --noprompt 2>&1 > /dev/null

if [ $CDB_EXISTS -eq 0 ]; then
        echo "
        CREATE ROLE crucible WITH LOGIN PASSWORD 'crucible' VALID UNTIL 'infinity';
        CREATE DATABASE crucible WITH ENCODING='UTF8' OWNER=crucible TEMPLATE=template0 CONNECTION LIMIT=-1;" \
        | PGPASSWORD="$DB_ENV_DBPASS" psql -h $PSQL_IP -p $PSQL_PORT -d $DB_ENV_DB -U $DB_ENV_DBUSER -w
fi


# Make config link belong to crucible
chown crucible: /opt/atlassian/crucible/current/config.xml

# RUN_AS: The user to run fisheye as. Its recommended that you create a separate user account for security reasons
RUN_AS=crucible
 
# FISHEYE_HOME: The path to the FishEye installation. Its recommended to create a symbolic link to the latest version so
# the process will still work after upgrades.
FISHEYE_HOME="/opt/atlassian/crucible/current"
 
# FISHEYE_INST: The path to store Fisheye data.
# The line below should be uncommented only if you don't have the environment variables set in /etc/environment file.
FISHEYE_INST="/opt/atlassian/crucible/data"
fisheyectl() {
        if [ "x$USER" != "x$RUN_AS" ]; then
                su - "$RUN_AS" -c "$FISHEYE_HOME/bin/fisheyectl.sh $1"
        else
                "$FISHEYE_HOME/bin/fisheyectl.sh" "$1"
        fi
}
 
case "$1" in
        start)
                fisheyectl start
		echo "`ps -A -o pid,cmd|grep /usr/bin/java | grep -v grep |head -n 1 | awk '{print $1}'`" >> /crucible.PID
                ;;
        stop)
                fisheyectl stop
		rm -f /crucible.PID
                ;;
        restart)
                fisheyectl stop
		rm -f /crucible.PID
                sleep 10
                fisheyectl start
		echo "`ps -A -o pid,cmd|grep /usr/bin/java | grep -v grep |head -n 1 | awk '{print $1}'`" >> /crucible.PID
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
esac
 
exit 0
