#!/bin/bash
 
# RUN_AS: The user to run fisheye as. Its recommended that you create a separate user account for security reasons
RUN_AS=crucible
 
# FISHEYE_HOME: The path to the FishEye installation. Its recommended to create a symbolic link to the latest version so
# the process will still work after upgrades.
FISHEYE_HOME="/opt/atlassian/crucible/current"
 
# FISHEYE_INST: The path to store Fisheye data.
# The line below should be uncommented only if you don't have the environment variables set in /etc/environment file.
FISHEYE_INST="/opt/atlassian/crucible/data"
fisheyectl() {
        if [ "x$USER" != "x$RUN_AS" ]; then
                su - "$RUN_AS" -c "$FISHEYE_HOME/bin/fisheyectl.sh $1"
        else
                "$FISHEYE_HOME/bin/fisheyectl.sh" "$1"
        fi
}
 
case "$1" in
        start)
                fisheyectl start
		echo "`ps -A -o pid,cmd|grep /usr/bin/java | grep -v grep |head -n 1 | awk '{print $1}'`" >> /crucible.PID
                ;;
        stop)
                fisheyectl stop
		rm -f /crucible.PID
                ;;
        restart)
                fisheyectl stop
		rm -f /crucible.PID
                sleep 10
                fisheyectl start
		echo "`ps -A -o pid,cmd|grep /usr/bin/java | grep -v grep |head -n 1 | awk '{print $1}'`" >> /crucible.PID
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
esac
 
exit 0
